/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Html } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'
import { TextureLoader } from 'three/src/loaders/TextureLoader'

export default function MachineZaal(props) {
 const { nodes, materials } = useGLTF('./models/machinezaal.glb')
 const colorMap = useLoader(TextureLoader, './models/textures/machinezaal-baked.jpg')
 colorMap.flipY = false

 const isClicked = useRef(false)

  return (
    <group {...props} dispose={null} >
      <group
        position={[-0.005, 0.584, -1.317]}
        rotation={[0, -1.568, 0]}
        scale={[1.293, 0.597, 0.331]}>
        <mesh
          onClick={() => isClicked.current = !isClicked.current}
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials['Material.001']}
          >
          <meshStandardMaterial 
          map={ colorMap} 
          emissive="#BC78FF" 
          emissiveIntensity={ isClicked.current ? 3 : 0 }
          toneMapped= { false } 
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_1.geometry}
          // material={materials.roof}
          >
          <meshStandardMaterial 
          map={colorMap} 
          emissive="#BC78FF" 
          emissiveIntensity={ isClicked.current ? 3 : 0 }
          toneMapped= { false } />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('./models/building-22.glb')
