/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Html } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'
import { TextureLoader } from 'three/src/loaders/TextureLoader'

export default function MainBuilding(props) {
  const { nodes, materials } = useGLTF('./models/building-22.glb')
  const colorMap = useLoader(TextureLoader, './models/textures/main-building-baked.jpg')
  colorMap.flipY = false
  
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={materials.roof}
        position={[-1.765, 1.692, -1.795]}
        rotation={[Math.PI, -1.559, Math.PI]}
        scale={[0.476, 0.053, 0.167]}
      >
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        position={[-1.771, 0.773, -1.926]}
        rotation={[0, -0.005, 0]}
        scale={[1.0, 1.0, 1.0]}
        // scale={[0.336, 0.792, 0.68]}
      >
        <meshStandardMaterial 
        map={colorMap} />
      <Html center
            position={ [0,1.0,0]}
            wrapperClass="mapPin"
            distanceFactor={ 6 }>
                <div>
                    <p className="mapPin__name">Main Building</p>
                    <p className="mapPin__desc">Events: 4</p>
                </div>
      </Html>
      </mesh>
    </group>
  )
}

useGLTF.preload('./models/building-22.glb')
