/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'
import { TextureLoader } from 'three/src/loaders/TextureLoader'

export default function Mechaniekers(props) {
const { nodes, materials } = useGLTF('./models/mechaniekers.glb')
const colorMap = useLoader(TextureLoader, './models/textures/mechaniekers-baked.jpg')
colorMap.flipY = false

  return (
    <group {...props} dispose={null}>
      <group
        position={[0.573, 0.306, 0.635]}
        rotation={[0, 0.009, 0]}
        scale={[0.209, 0.324, 0.624]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={materials.building}
        >
          <meshStandardMaterial 
          map={colorMap} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_1.geometry}
          material={materials.roof}
        >
          <meshStandardMaterial 
          map={colorMap} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('./models/mechaniekers.glb')
